# Clustering

Cuando se conoce el número de clusters:    
* K-Means
* Spectral Clustering
    
Cuando se desconoce el número de clusters:
* Meanshift
* Cluster jerarquico
* DBscan

In [10]:
import pandas as pd
import numpy as np

from sklearn.cluster import MiniBatchKMeans, MeanShift

from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv("candy.csv")

X = dataset.drop(["competitorname"], axis=1)

In [3]:
X.head()

chocolate  fruity  caramel  peanutyalmondy  nougat  crispedricewafer  hard  \
0          1       0        1               0       0                 1     0   
1          1       0        0               0       1                 0     0   
2          0       0        0               0       0                 0     0   
3          0       0        0               0       0                 0     0   
4          0       1        0               0       0                 0     0   

   bar  pluribus  sugarpercent  pricepercent  winpercent  
0    1         0         0.732         0.860   66.971725  
1    1         0         0.604         0.511   67.602936  
2    0         0         0.011         0.116   32.261086  
3    0         0         0.011         0.511   46.116505  
4    0         0         0.906         0.511   52.341465

## KMeans

In [4]:
kmeans = MiniBatchKMeans(n_clusters=4, batch_size=8).fit(X)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1934: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=3)


In [7]:
kmeans.cluster_centers_

array([[5.12820513e-02, 4.10256410e-01, 1.28205128e-01, 1.02564103e-01,
        0.00000000e+00, 0.00000000e+00, 3.58974359e-01, 0.00000000e+00,
        7.43589744e-01, 3.35769229e-01, 3.23948713e-01, 3.04727542e+01],
       [3.88888889e-01, 5.55555556e-01, 8.33333333e-02, 1.75925926e-01,
        1.20370370e-01, 2.77777778e-02, 1.48148148e-01, 2.31481481e-01,
        5.74074074e-01, 4.60953697e-01, 4.47166665e-01, 5.09368781e+01],
       [8.09523810e-01, 1.90476190e-01, 3.09523810e-01, 2.97619048e-01,
        1.19047619e-01, 2.85714286e-01, 1.19047619e-02, 5.23809524e-01,
        3.57142857e-01, 5.31869039e-01, 6.03202386e-01, 6.79807765e+01],
       [2.02247191e-01, 6.40449438e-01, 6.74157303e-02, 0.00000000e+00,
        6.74157303e-02, 0.00000000e+00, 3.03370787e-01, 6.74157303e-02,
        6.40449438e-01, 4.78831453e-01, 3.74348309e-01, 3.92766517e+01]])

In [8]:
kmeans.predict(X)

array([2, 2, 0, 1, 1, 1, 1, 0, 3, 0, 3, 3, 0, 3, 3, 3, 3, 1, 1, 0, 1, 3,
       1, 2, 1, 1, 0, 1, 2, 3, 3, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 2, 2,
       0, 3, 1, 2, 3, 3, 3, 2, 2, 2, 2, 3, 2, 0, 3, 0, 2, 1, 3, 1, 2, 2,
       2, 1, 2, 0, 0, 0, 0, 1, 1, 3, 1, 1, 1, 2, 1, 3, 3, 3, 1])

In [9]:
dataset['group_kmeans'] = kmeans.predict(X)
dataset.head()

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
0      100 Grand          1       0        1               0       0   
1   3 Musketeers          1       0        0               0       1   
2       One dime          0       0        0               0       0   
3    One quarter          0       0        0               0       0   
4      Air Heads          0       1        0               0       0   

   crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0                 1     0    1         0         0.732         0.860   
1                 0     0    1         0         0.604         0.511   
2                 0     0    0         0         0.011         0.116   
3                 0     0    0         0         0.011         0.511   
4                 0     0    0         0         0.906         0.511   

   winpercent  group  
0   66.971725      2  
1   67.602936      2  
2   32.261086      0  
3   46.116505      1  
4   52.341465      1

## Meanshift

In [11]:
meanshift = MeanShift().fit(X)

In [12]:
dataset['group_meanshift'] = meanshift.predict(X)
dataset.head()

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
0      100 Grand          1       0        1               0       0   
1   3 Musketeers          1       0        0               0       1   
2       One dime          0       0        0               0       0   
3    One quarter          0       0        0               0       0   
4      Air Heads          0       1        0               0       0   

   crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0                 1     0    1         0         0.732         0.860   
1                 0     0    1         0         0.604         0.511   
2                 0     0    0         0         0.011         0.116   
3                 0     0    0         0         0.011         0.511   
4                 0     0    0         0         0.906         0.511   

   winpercent  group  group_meanshift  
0   66.971725      2                2  
1   67.602936      2                2  
2   32.261086      0                0  
3   46.116505      1                0  
4   52.341465      1                1

In [13]:
meanshift.labels_

array([2, 2, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 2, 1, 2, 0, 1, 2, 0, 0, 1, 2, 2, 0, 1, 2, 2, 2, 1, 1, 1, 2, 2,
       0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 2, 1, 0, 0, 2, 2,
       2, 1, 2, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 2, 0, 0, 0, 0, 1],
      dtype=int64)

In [15]:
meanshift.cluster_centers_

array([[2.25000000e-01, 5.75000000e-01, 1.00000000e-01, 2.50000000e-02,
        5.00000000e-02, 2.50000000e-02, 3.00000000e-01, 1.00000000e-01,
        5.50000000e-01, 4.57599993e-01, 3.67824996e-01, 4.10442122e+01],
       [4.68750000e-01, 5.00000000e-01, 1.25000000e-01, 1.56250000e-01,
        9.37500000e-02, 6.25000000e-02, 1.25000000e-01, 3.12500000e-01,
        5.31250000e-01, 4.57281243e-01, 4.67874998e-01, 5.21138597e+01],
       [8.26086957e-01, 1.73913043e-01, 3.04347826e-01, 3.04347826e-01,
        1.73913043e-01, 1.73913043e-01, 0.00000000e+00, 5.21739130e-01,
        4.34782609e-01, 5.81391293e-01, 6.38086963e-01, 6.47120799e+01]])

In [17]:
meanshift.predict(X)

array([2, 2, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 2, 1, 2, 0, 1, 2, 0, 0, 1, 2, 2, 0, 1, 2, 2, 2, 1, 1, 1, 2, 2,
       0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 2, 1, 0, 0, 2, 2,
       2, 1, 2, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 2, 0, 0, 0, 0, 1],
      dtype=int64)